const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
test('Scheme loads sections, opens no method until one is picked, and retains Parts after another click', () => {
  const html = fs.readFileSync(process.env.VERTEX_METRICS_HTML || require('node:path').join(__dirname, '../../org.vertex.abap.ui/resources/metrics.html'), 'utf8');
  const elements = {};
  const node = () => ({children: [], classList: {toggle() {}}, appendChild(n) {this.children.push(n);}, addEventListener() {}, set innerHTML(v) {this.children=[];}});
  const ctx = vm.createContext({document: {getElementById(id) {return elements[id] ||= node();}, createTextNode(text) {return {...node(), textContent:text};}, createElement: node, body: node()}, window: {}, console});
  vm.runInContext(html.match(/<script>([\s\S]*?)<\/script>/)[1].split('/* ---------- wiring ---------- */')[0], ctx);
  vm.runInContext(`var INITIAL = null; loadedObject='ZCL_TEST'; loadedType='CLAS';
    units=[{unit_name:'ZCL_TEST=>first',unit_type:'method',include:'one'},{unit_name:'ZCL_TEST=>second',unit_type:'method',include:'two'}];
    var reads=0, requests=0; sdeClass=function(){reads++;}; requestDiagram=function(){requests++;};
    INITIAL={action:'scheme'}; loadedObject=null;
    render({object:'ZCL_TEST',type:'CLAS',units:units,totals:{}});`, ctx);
  assert.equal(ctx.reads, 1);
  assert.equal(elements.root.children.length, 0, 'Do not render intermediate Other or metrics tables');
  ctx.answered('scheme-parts', JSON.stringify({nodes:[{name:'ZCL_TEST',methods:[{name:'first',visibility:'public'},{name:'second',visibility:'private'}]}]}));
  // Nothing was named, so nothing is opened for the reader.
  assert.equal(ctx.shownUnit, null);
  ctx.openUnit(ctx.units[0]);
  assert.equal(ctx.shownUnit.name, 'ZCL_TEST=>first');
  const table = elements.root.children[2];
  const rows = ctx.schemeRows.map(row => row.element);
  elements.list.scrollTop = 123;
  ctx.openUnit(ctx.units[1]);
  assert.equal(elements.root.children[2], table, 'Keep the same table on method click');
  assert.equal(ctx.schemeRows[0].element, rows[0]);
  assert.equal(ctx.schemeRows[1].element, rows[1]);
  assert.equal(rows[0].className, 'pick');
  assert.equal(rows[1].className, 'pick sel');
  assert.equal(elements.list.scrollTop, 123);
  assert.equal(ctx.shownUnit.name, 'ZCL_TEST=>second');
  assert.equal(elements.root.className, 'uml-parts');
  const text = n => [n.textContent || '', ...n.children.map(text)].join(' ');
  assert.match(text(elements.root), /CPUB.*METH.*first.*CPRI.*METH.*second/);
  assert.equal(ctx.requests, 2);
});
