CLASS zcl_vx_review_prepare DEFINITION
  PUBLIC
  FINAL
  CREATE PRIVATE.

  PUBLIC SECTION.
    TYPES ty_part_row TYPE zif_vx_vers_types=>ty_part_row.
    TYPES ty_t_part_row TYPE zif_vx_vers_types=>ty_t_part_row.
    TYPES ty_version_row TYPE zif_vx_vers_types=>ty_version_row.
    TYPES ty_t_version_row TYPE zif_vx_vers_types=>ty_t_version_row.
    TYPES ty_t_selected_keys TYPE HASHED TABLE OF string WITH UNIQUE KEY table_line.
    TYPES ty_t_korr_found TYPE zif_vx_review_types=>ty_t_korr_found.
    TYPES:
      BEGIN OF ty_author_lookup,
        author     TYPE versuser,
        diag_lines TYPE string_table,
      END OF ty_author_lookup.
    CLASS-METHODS is_selected_only
      IMPORTING
        iv_keys          TYPE string
      RETURNING
        VALUE(result)    TYPE abap_bool.

    CLASS-METHODS parse_selected_keys
      IMPORTING
        iv_keys          TYPE string
      RETURNING
        VALUE(result)    TYPE ty_t_selected_keys.

    CLASS-METHODS part_key
      IMPORTING
        is_part          TYPE ty_part_row
      RETURNING
        VALUE(result)    TYPE string.

    CLASS-METHODS count_supported_parts
      IMPORTING
        it_parts         TYPE ty_t_part_row
      RETURNING
        VALUE(result)    TYPE i.

    CLASS-METHODS count_preparable_parts
      IMPORTING
        it_parts           TYPE ty_t_part_row
        iv_selected_only   TYPE abap_bool
        it_selected_keys   TYPE ty_t_selected_keys
        "! Mirrors the "Ignore SAP generated" setting: when off, generated
        "! classes are prepared like any other object and must be counted.
        iv_ignore_generated TYPE abap_bool DEFAULT abap_true
      RETURNING
        VALUE(result)      TYPE i.

    CLASS-METHODS has_part_key
      IMPORTING
        it_parts         TYPE ty_t_part_row
        iv_key           TYPE string
      RETURNING
        VALUE(result)    TYPE abap_bool.

    CLASS-METHODS get_created_object_author
      IMPORTING
        is_part          TYPE ty_part_row
      RETURNING
        VALUE(result)    TYPE ty_author_lookup.

    "! True when a class section source (CPUB/CPRO/CPRI include) carries nothing
    "! but its own section header, e.g. a newly generated class always contains
    "! 'protected section.' even when nothing is declared there. Such a section is
    "! not a reviewable change.
    CLASS-METHODS is_empty_section
      IMPORTING
        it_source        TYPE abaptxt255_tab
      RETURNING
        VALUE(result)    TYPE abap_bool.

    CLASS-METHODS is_comments_only
      IMPORTING
        it_source        TYPE abaptxt255_tab
      RETURNING
        VALUE(result)    TYPE abap_bool.

    "! True for an auto-generated header comment that carries the generation
    "! timestamp or the generator version:
    "!   '*&* This class has been generated on <ts> in client <nnn>'  (SEGW)
    "!   '*   generation date:  01.07.2025 at 13:29:40'               (table
    "!   '*   view maintenance generator version: #001407#'            maint.)
    "! Such lines differ on every regeneration and are a false positive in code
    "! review. Used for the review diff and the retrofit diff alike, so what one
    "! ignores never shows up as a moving violation in the other.
    CLASS-METHODS is_generated_ts_line
      IMPORTING
        iv_line          TYPE clike
      RETURNING
        VALUE(result)    TYPE abap_bool.

    "! True when the version author is a SAP technical/generation user
    "! (mask 'SAP*'). Such code — e.g. the function-group framework includes
    "! SAPL<area> / L<area>UXX — is auto-generated by SAP and must not appear
    "! as a reviewable change nor as a developer in the Code Review report.
    CLASS-METHODS is_sap_generated_author
      IMPORTING
        iv_author        TYPE clike
      RETURNING
        VALUE(result)    TYPE abap_bool.

    "! True for code SAP generates, which must stay out of Code Review while
    "! "Ignore SAP generated" is on:
    "!
    "! - the Gateway/SEGW classes <name>_MPC, <name>_MPC_EXT and <name>_DPC,
    "!   regenerated from the OData model. <name>_DPC_EXT is deliberately NOT
    "!   matched — that is where the service implementation is written by hand
    "!   and it stays reviewable;
    "! - the function group main program SAPL<area>: the include list SAP
    "!   rewrites itself whenever a function module is added. It carries the
    "!   name of whoever added it, so IS_SAP_GENERATED_AUTHOR (mask 'SAP*')
    "!   never catches it, and what it shows is an INCLUDE line nobody wrote.
    "!
    "! Accepts a plain class name as well as a VRSD part name, where the class is
    "! padded with '=' (section includes) or blanks (METH).
    "! The name says "class" for the callers' sake and now covers more than one;
    "! renaming it to IS_GENERATED_OBJECT touches nine call sites and is a
    "! separate change.
    CLASS-METHODS is_generated_class
      IMPORTING
        iv_name          TYPE clike
      RETURNING
        VALUE(result)    TYPE abap_bool.

    "! True when the object of this part is gone from the system while its
    "! version history is not: VRSD/VRSS survive a deletion by design (that is
    "! how a deleted object can still be retrieved from version management), so a
    "! deleted program keeps every version it ever had. Code Review would pair
    "! the newest of them against nothing and present the whole source as freshly
    "! written code that nobody can look at any more — 136 green lines of a
    "! program SE38 reports as non-existent. Uses the same existence check as the
    "! Versions Explorer parts list, which paints such a row red.
    CLASS-METHODS is_deleted_object
      IMPORTING
        is_part          TYPE ty_part_row
      RETURNING
        VALUE(result)    TYPE abap_bool.

    "! "Comment check" — the P_CMTCHK setting. It gates the marks, not the
    "! check: the verdict is decided on every Prepare run because it is cheap,
    "! and ticking the checkbox then marks the review that is already there.
    "! Off, nothing of it is drawn at all.
    CLASS-DATA gv_comment_check TYPE abap_bool.

    "! Change description of a whole object: does the request add a full-line
    "! comment naming a transport request in the LEADING comment area of the new
    "! source — before the first line of code?
    "!
    "!   *----------------------------------------------------------------*
    "!   * Date       |Author   |Transport | Change ID - Description       *
    "!   * 08.07.2026 |CT818300 |ER6K9A1JDL| DMND0004398 - Rotation rest    *
    "!   *----------------------------------------------------------------*
    "!   MODULE status_0100 OUTPUT.          <- the first code line ends it
    "!
    "! Two things are deliberately NOT enough. A note behind a statement —
    "! `et_rota_balan = DATA(lt_rota_balan). " Added by CT813017 ER6K9A1JDL` —
    "! carries the request number and satisfies the per-block rule, but it is
    "! not a description of the object: a reader opening the object still finds
    "! nothing at the top. And a full-line comment 400 lines down is not the
    "! header either, which is why the position is part of the rule.
    "!
    "! The statement that OPENS the part (REPORT / FUNCTION / METHOD / MODULE /
    "! …) does not end the leading area: the convention writes the block under
    "! it, and a method source read from the active state carries its own
    "! METHOD line.
    CLASS-METHODS diff_has_change_descr
      IMPORTING
        it_diff          TYPE zif_vx_vers_types=>ty_t_diff
      RETURNING
        VALUE(result)    TYPE abap_bool.

    "! Does the comment control apply to this part at all? Two exemptions, and
    "! both are code nobody writes by hand:
    "!
    "! A **class section** (CPUB/CPRO/CPRI, and the CLSD definition with it)
    "! holds declarations, not code, SAP regenerates it in an arbitrary order
    "! (which is why ZCL_VX_DIFF_DECL exists), and there is no place in it for
    "! a change-history line — the convention lives in the method that uses the
    "! declaration. "The first block is the change description" means nothing
    "! there either: a section has no top of an object.
    "!
    "! The **function group main program**, SAPL<area>, is the include list SAP
    "! writes itself: adding a function module rewrites it, under the name of
    "! whoever added it, so neither the author rule (IS_SAP_GENERATED_AUTHOR)
    "! nor a comment convention reaches it. An INCLUDE line has nowhere to
    "! carry a request number and nobody put it there to begin with.
    CLASS-METHODS comment_check_applies
      IMPORTING
        iv_objtype       TYPE versobjtyp
        iv_objname       TYPE versobjnam OPTIONAL
      RETURNING
        VALUE(result)    TYPE abap_bool.

    "! The requests this review is about: the entered ones, their S/R tasks and
    "! the parent K of a task. A block that names a CTS number outside this set
    "! documents a change under somebody else's request — most often a typo one
    "! character off (ER6K9A1JD**T** written into a review of ER6K9A1JD**L**),
    "! which is exactly what nobody notices by reading. Empty = no request scope
    "! (package or plain object review), and then any number is accepted.
    CLASS-DATA gt_scope_korr TYPE HASHED TABLE OF trkorr WITH UNIQUE KEY table_line.

    "! Fills GT_SCOPE_KORR. The caller passes everything the review answers to:
    "! the requests as entered on the selection screen, the S/R tasks they were
    "! expanded into, and the parent K of a task.
    CLASS-METHODS set_review_scope
      IMPORTING
        it_korrnums      TYPE zif_vx_object=>ty_t_korr_range.

    "! Comment control of one changed block, in one verdict:
    "!   'X' its new lines name a request of this review
    "!   'R' they name a request of ANOTHER system — retrofitted code, marked
    "!       but not faulted
    "!   'V' the same, and that request is in this object's own version history
    "!       here: the code really did arrive from there, the note is confirmed
    "!   'N' they name a request of THIS system that does not exist here — a
    "!       number typed wrong, the hardest fact of them all
    "!   'T' they name a TASK of this system. The convention writes the
    "!       transport request (type K) the work moves under, not the task it
    "!       was typed in
    "!   'W' they name a request of this system that exists but is not ours
    "!   '-' they name no request at all
    "! A block that names both a foreign number and one of ours passes: the
    "! change is documented under this request, whatever else stands next to it.
    CLASS-METHODS block_request_verdict
      IMPORTING
        it_lines         TYPE string_table
        "! Requests recorded in the version history of THIS object in THIS
        "! system. An import writes the source request into VRSD, so a foreign
        "! number found here proves the code did travel from there — which is
        "! the one thing E070 cannot answer for another system's request.
        "! Absence proves nothing (the request may have touched other objects
        "! only), so it downgrades the mark instead of faulting it.
        it_obj_korrnums  TYPE ty_t_korr_found OPTIONAL
      RETURNING
        VALUE(result)    TYPE zif_vx_review_types=>ty_req_ref.

    "! Statement tracking for block grouping. One ABAP statement must not be
    "! cut into two blocks: a call whose opening line carries the change comment
    "! ended in one block and its parameters in the next, so the second block
    "! was reported as undocumented and both had to be approved separately.
    "! The rule that decides where a block ends is "a few context lines after";
    "! this makes it "as many as the statement needs".
    "!
    "! CV_OPEN says whether the line just consumed left a statement unfinished.
    "! A blank or a full-line comment says nothing and leaves it as it was; a
    "! line of code closes the statement when its code part ends with '.'.
    "! Fed with the NEW side only ('=' and '+'): a deleted line is not part of
    "! the source the blocks are cut from.
    CLASS-METHODS update_stmt_open
      IMPORTING
        iv_line          TYPE clike
      CHANGING
        cv_open          TYPE abap_bool.

    "! Ceiling for that bridging, so a statement the parser fails to see the end
    "! of cannot swallow a whole object into one block.
    CONSTANTS c_stmt_bridge_max TYPE i VALUE 100.

    "! Comment control, one source line: does it name a transport request in a
    "! comment? Both spellings of the shop convention count — the change-history
    "! header at the top of an object
    "!   * 27-07-2026 |CT770028 |ER6K9A1JDL| DMND0004398 extra hiding
    "! and the note behind a single statement
    "!   it_rota_balan = lt_rota_balan  " Added by CT813017 ER6K9A1JDL
    "! Only the CTS number decides. The ticket ids written next to it
    "! (RLSE0027352, DMND0004398) are a per-shop habit, the request number is not,
    "! and it is the one thing that ties the line back to what moved it.
    CLASS-METHODS line_names_request
      IMPORTING
        iv_line          TYPE clike
      RETURNING
        VALUE(result)    TYPE abap_bool.

    "! The same control for one changed block: its NEW lines are the ones the
    "! developer wrote, so they are the ones that have to carry the request.
    "! A block that only deletes lines has nowhere to name it and fails the
    "! check by construction — which is the intended answer: code is commented
    "! out with the request number, not silently dropped.
    CLASS-METHODS block_names_request
      IMPORTING
        it_lines         TYPE string_table
      RETURNING
        VALUE(result)    TYPE abap_bool.

    "! Removes the 'METHOD <name>.' / 'ENDMETHOD.' frame from a method source.
    "! The two sides of a retrofit comparison do not agree on it: an ACTIVE read
    "! brings the frame, a versioned read returns the body alone. Two phantom
    "! lines at both ends is not the worst of it — the leading one anchors the
    "! whole LCS one line off. Stripping both sides makes them comparable.
    "! A source that has no frame is returned unchanged.
    CLASS-METHODS strip_method_wrapper
      IMPORTING it_src        TYPE abaptxt255_tab
      RETURNING VALUE(result) TYPE abaptxt255_tab.

    "! Neutralizes diff hunks whose only change is the generated-timestamp
    "! header line: a '-'/'+' pair on that line is collapsed to an unchanged
    "! ('=') context line so it no longer shows up as a review change. Real
    "! edits (including standalone add/delete of such a line) are preserved.
    CLASS-METHODS strip_generated_ts_diff
      IMPORTING
        it_diff          TYPE zif_vx_vers_types=>ty_t_diff
      RETURNING
        VALUE(result)    TYPE zif_vx_vers_types=>ty_t_diff.

  PRIVATE SECTION.
    TYPES: BEGIN OF ty_korr_known,
             korrnum TYPE trkorr,
             exists  TYPE abap_bool,
             is_task TYPE abap_bool,
           END OF ty_korr_known.
    CLASS-DATA gt_korr_exists TYPE HASHED TABLE OF ty_korr_known WITH UNIQUE KEY korrnum.

    "! Alphanumerics, the only characters a request number is made of: they
    "! separate one token of a comment from the next, so '|ER6K9A1JDL|' and
    "! '(ER6K9A1JDL)' are read the same way.
    CONSTANTS c_alnum TYPE string VALUE `ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789`.
    CONSTANTS c_letters TYPE string VALUE `ABCDEFGHIJKLMNOPQRSTUVWXYZ`.
    CONSTANTS c_digits TYPE string VALUE `0123456789`.

    "! Every CTS number named in the comment of one line.
    CLASS-METHODS line_request_refs
      IMPORTING
        iv_line          TYPE clike
      CHANGING
        ct_refs          TYPE ty_t_korr_found.

    "! Is this request number one of the review's own?
    CLASS-METHODS korr_in_scope
      IMPORTING
        iv_korr          TYPE trkorr
      RETURNING
        VALUE(result)    TYPE abap_bool.

    "! Was this request created in another system? The first three characters
    "! of a CTS number are the system it was created in, so this needs no P_SYS
    "! and no call into that system: a number whose SID is not ours cannot be a
    "! request of this system at all.
    "! KEEP (replaced): this used to compare against GV_REMOTE_SID (P_SYS) —
    "! which left every foreign number unrecognised whenever the remote system
    "! was not filled in, and those are exactly the reviews where nobody is
    "! thinking about the other system.
    CLASS-METHODS is_other_system_korr
      IMPORTING
        iv_korr          TYPE trkorr
      RETURNING
        VALUE(result)    TYPE abap_bool.

    "! E070 of THIS system for one number: does it exist, and is it a task?
    "! Answerable only for our own SID — E070 is local, a request of another
    "! system is not in it and its absence proves nothing. Cached: the same
    "! number appears on every line of a change-history header.
    CLASS-METHODS korr_type
      IMPORTING
        iv_korr          TYPE trkorr
      EXPORTING
        ev_exists        TYPE abap_bool
        ev_is_task       TYPE abap_bool.

    "! A line that is nothing but a comment: ABAP `*` or `"` in the first
    "! column, CDS `//`. Expects an already condensed line.
    CLASS-METHODS is_full_line_comment
      IMPORTING
        iv_line          TYPE string
      RETURNING
        VALUE(result)    TYPE abap_bool.

    "! The statement that opens a part — REPORT / PROGRAM / FUNCTION /
    "! FUNCTION-POOL / METHOD / FORM / MODULE / CLASS / INTERFACE. Expects an
    "! already condensed line.
    CLASS-METHODS is_opening_statement
      IMPORTING
        iv_line          TYPE string
      RETURNING
        VALUE(result)    TYPE abap_bool.

    "! The comment part of one source line, upper case: the whole line when it
    "! is a comment line, everything behind the first '"' otherwise, empty when
    "! there is no comment on it.
    CLASS-METHODS comment_of
      IMPORTING
        iv_line          TYPE clike
      RETURNING
        VALUE(result)    TYPE string.

    "! True for a token shaped like a CTS request number: <SID>K<6>, e.g.
    "! ER6K947305 or ER6K9A1JDL. The category letter is pinned to K/T on
    "! purpose — left open, ordinary ten-letter words in prose passed for
    "! request numbers.
    CLASS-METHODS is_request_number
      IMPORTING
        iv_token         TYPE string
      RETURNING
        VALUE(result)    TYPE abap_bool.

    CLASS-METHODS flush_ts_run
      CHANGING
        ct_del TYPE zif_vx_vers_types=>ty_t_diff
        ct_ins TYPE zif_vx_vers_types=>ty_t_diff
        ct_out TYPE zif_vx_vers_types=>ty_t_diff.
ENDCLASS.


CLASS zcl_vx_review_prepare IMPLEMENTATION.

  METHOD is_selected_only.
    result = xsdbool( iv_keys IS NOT INITIAL AND iv_keys <> `0` ).
  ENDMETHOD.


  METHOD parse_selected_keys.
    CHECK is_selected_only( iv_keys ) = abap_true.

    SPLIT iv_keys AT `;` INTO TABLE DATA(lt_selected_raw).
    LOOP AT lt_selected_raw INTO DATA(lv_selected_raw).
      CHECK lv_selected_raw IS NOT INITIAL.
      INSERT lv_selected_raw INTO TABLE result.
    ENDLOOP.
  ENDMETHOD.


  METHOD part_key.
    result = |{ is_part-type }~{ is_part-object_name }|.
  ENDMETHOD.


  METHOD count_supported_parts.
    LOOP AT it_parts INTO DATA(ls_part) WHERE type <> 'RPT'.
      IF zcl_vx_vers_data=>is_supported_object_type( ls_part-type ) = abap_true.
        result = result + 1.
      ENDIF.
    ENDLOOP.
  ENDMETHOD.


  METHOD count_preparable_parts.
    LOOP AT it_parts INTO DATA(ls_part) WHERE type <> 'RPT'.
      IF zcl_vx_vers_data=>is_supported_object_type( ls_part-type ) = abap_false.
        CONTINUE.
      ENDIF.
      " Skipped by the workflow as well — counting them would leave the progress
      " short of 100% for the whole run.
      IF iv_ignore_generated = abap_true
         AND ( is_generated_class( ls_part-object_name ) = abap_true
            OR ( ls_part-class IS NOT INITIAL
             AND is_generated_class( ls_part-class ) = abap_true ) ).
        CONTINUE.
      ENDIF.
      " Deleted objects are skipped by the workflow too.
      IF is_deleted_object( ls_part ) = abap_true.
        CONTINUE.
      ENDIF.
      IF iv_selected_only = abap_true
         AND NOT line_exists( it_selected_keys[ table_line = part_key( ls_part ) ] ).
        CONTINUE.
      ENDIF.
      result = result + 1.
    ENDLOOP.
  ENDMETHOD.


  METHOD has_part_key.
    LOOP AT it_parts INTO DATA(ls_part) WHERE type <> 'RPT'.
      IF iv_key = part_key( ls_part ).
        result = abap_true.
        RETURN.
      ENDIF.
    ENDLOOP.
  ENDMETHOD.


  METHOD get_created_object_author.
    DATA(lv_tadir_object) = CONV tadir-object( is_part-type ).
    DATA(lv_tadir_name) = CONV tadir-obj_name( is_part-object_name ).

    CASE is_part-type.
      WHEN 'REPS' OR 'REPT'.
        lv_tadir_object = 'PROG'.
      WHEN 'METH'.
        IF is_part-class IS NOT INITIAL.
          DATA lv_meth_cl_key TYPE seoclskey.
          DATA lt_meth_includes TYPE seop_methods_w_include.
          lv_meth_cl_key = is_part-class.
          CALL FUNCTION 'SEO_CLASS_GET_METHOD_INCLUDES'
            EXPORTING
              clskey   = lv_meth_cl_key
            IMPORTING
              includes = lt_meth_includes
            EXCEPTIONS
              _internal_class_not_existing = 1
              OTHERS                       = 2.
          IF sy-subrc = 0.
            DATA lv_meth_include TYPE seop_method_w_include.
            LOOP AT lt_meth_includes INTO lv_meth_include.
              IF lv_meth_include-cpdkey-cpdname = is_part-name.
                EXIT.
              ENDIF.
              CLEAR lv_meth_include.
            ENDLOOP.
            IF lv_meth_include IS NOT INITIAL.
              " Use UNAM (last changed by) not CNAM (created by): the change
              " author is whoever last touched the include — i.e. the author of
              " the selected (S) request, not the ancient original creator.
              DATA lv_reposrc_unam TYPE reposrc-unam.
              SELECT SINGLE unam FROM reposrc
                WHERE progname = @lv_meth_include-incname
                INTO @lv_reposrc_unam.
              IF sy-subrc = 0 AND lv_reposrc_unam IS NOT INITIAL.
                result-author = lv_reposrc_unam.
                APPEND |METH AUTHOR { is_part-object_name }: include { lv_meth_include-cpdkey-cpdname }, REPOSRC-UNAM={ lv_reposrc_unam }| TO result-diag_lines.
              ELSE.
                APPEND |METH AUTHOR { is_part-object_name }: include { lv_meth_include-cpdkey-cpdname }, REPOSRC-UNAM not found, fallback to TADIR| TO result-diag_lines.
                lv_tadir_object = 'CLAS'.
                lv_tadir_name = CONV tadir-obj_name( is_part-class ).
              ENDIF.
            ELSE.
              APPEND |METH AUTHOR { is_part-object_name }: include not found in SEO_CLASS_GET_METHOD_INCLUDES, fallback to TADIR| TO result-diag_lines.
              lv_tadir_object = 'CLAS'.
              lv_tadir_name = CONV tadir-obj_name( is_part-class ).
            ENDIF.
          ELSE.
            APPEND |METH AUTHOR { is_part-object_name }: SEO_CLASS_GET_METHOD_INCLUDES failed (subrc={ sy-subrc }), fallback to TADIR| TO result-diag_lines.
            lv_tadir_object = 'CLAS'.
            lv_tadir_name = CONV tadir-obj_name( is_part-class ).
          ENDIF.
          IF result-author IS NOT INITIAL.
            CLEAR: lv_tadir_object, lv_tadir_name.
          ENDIF.
        ELSE.
          CLEAR: lv_tadir_object, lv_tadir_name.
          APPEND |NEW OBJECT { is_part-type } { is_part-object_name }: skip TADIR author lookup, parent class is unknown| TO result-diag_lines.
        ENDIF.
      WHEN 'CLSD' OR 'CPUB' OR 'CPRO' OR 'CPRI' OR 'CINC' OR 'CDEF'.
        lv_tadir_object = 'CLAS'.
        IF is_part-class IS NOT INITIAL.
          lv_tadir_name = CONV tadir-obj_name( is_part-class ).
        ELSEIF lv_tadir_name CS '='.
          DATA(lv_tadir_eq_pos) = find( val = CONV string( lv_tadir_name ) sub = '=' ).
          IF lv_tadir_eq_pos > 0.
            lv_tadir_name = lv_tadir_name(lv_tadir_eq_pos).
          ENDIF.
        ENDIF.
    ENDCASE.

    IF lv_tadir_object IS NOT INITIAL AND lv_tadir_name IS NOT INITIAL.
      SELECT SINGLE author FROM tadir
        WHERE pgmid    = 'R3TR'
          AND object   = @lv_tadir_object
          AND obj_name = @lv_tadir_name
          AND delflag  = ' '
        INTO @result-author.
    ENDIF.
  ENDMETHOD.


  METHOD is_empty_section.
    LOOP AT it_source INTO DATA(ls_line).
      DATA(lv_trimmed) = condense( to_upper( CONV string( ls_line ) ) ).
      CHECK lv_trimmed IS NOT INITIAL.
      " Comment lines carry no declaration.
      IF lv_trimmed(1) = '*' OR lv_trimmed(1) = '"'.
        CONTINUE.
      ENDIF.
      IF lv_trimmed <> `PUBLIC SECTION.`
         AND lv_trimmed <> `PROTECTED SECTION.`
         AND lv_trimmed <> `PRIVATE SECTION.`.
        RETURN.
      ENDIF.
    ENDLOOP.
    result = abap_true.
  ENDMETHOD.


  METHOD strip_method_wrapper.
    result = it_src.

    DATA lv_open  TYPE i.
    DATA lv_close TYPE i.
    DATA lv_idx   TYPE i.

    LOOP AT result INTO DATA(ls_line).
      DATA(lv_up) = to_upper( condense( CONV string( ls_line ) ) ).
      IF lv_up IS INITIAL.
        CONTINUE.
      ENDIF.
      IF strlen( lv_up ) >= 7 AND lv_up(7) = 'METHOD '.
        lv_open = sy-tabix.
      ENDIF.
      EXIT.
    ENDLOOP.
    CHECK lv_open > 0.

    lv_idx = lines( result ).
    WHILE lv_idx > lv_open.
      DATA(lv_up_end) = to_upper( condense( CONV string( result[ lv_idx ] ) ) ).
      IF lv_up_end IS NOT INITIAL.
        IF lv_up_end = 'ENDMETHOD.' OR lv_up_end = 'ENDMETHOD'.
          lv_close = lv_idx.
        ENDIF.
        EXIT.
      ENDIF.
      lv_idx = lv_idx - 1.
    ENDWHILE.
    CHECK lv_close > 0.

    DELETE result INDEX lv_close.
    DELETE result INDEX lv_open.
  ENDMETHOD.


  METHOD is_comments_only.
    result = abap_true.
    LOOP AT it_source INTO DATA(ls_line).
      DATA(lv_trimmed) = condense( CONV string( ls_line ) ).
      CHECK lv_trimmed IS NOT INITIAL.
      IF lv_trimmed(1) <> '*'.
        result = abap_false.
        RETURN.
      ENDIF.
    ENDLOOP.
  ENDMETHOD.


  METHOD is_generated_ts_line.
    DATA(lv_up) = to_upper( condense( CONV string( iv_line ) ) ).

    " SEGW/gateway generator, e.g.
    "   *&* This class has been generated on 09.07.2026 15:31:07 in client 600
    IF lv_up CS 'HAS BEEN GENERATED ON' AND lv_up CS 'IN CLIENT'.
      result = abap_true.
      RETURN.
    ENDIF.

    " Function group / include regeneration stamp, e.g.
    "   * regenerated at 30.06.2026 16:56:30
    " The only line of the block is the moment the generator last ran, and it
    " differs in every system by construction.
    IF lv_up CS 'REGENERATED AT'.
      result = abap_true.
      RETURN.
    ENDIF.

    " Table maintenance generator (VIEWFRAME_*/function group of a maint. view):
    "   *   generation date:  01.07.2025 at 13:29:40
    "   *   view maintenance generator version: #001407#
    " Both are rewritten by every regeneration, in every system independently —
    " left alone they turn a re-generated maintenance view into a moving
    " violation whose whole content is the date it was generated on.
    result = xsdbool( lv_up CS 'GENERATION DATE:'
                   OR lv_up CS 'MAINTENANCE GENERATOR VERSION' ).
  ENDMETHOD.


  METHOD is_sap_generated_author.
    result = xsdbool( iv_author CP 'SAP*' ).
  ENDMETHOD.


  METHOD is_generated_class.
    DATA(lv_name) = to_upper( condense( CONV string( iv_name ) ) ).
    CHECK lv_name IS NOT INITIAL.

    " Cut the VRSD padding: 'ZCL_X_MPC=====...' (section include) or
    " 'ZCL_X_MPC        METHOD' (METH, blank-padded, condensed to one blank).
    DATA(lv_eq) = find( val = lv_name sub = '=' ).
    IF lv_eq > 0.
      lv_name = lv_name(lv_eq).
    ENDIF.
    DATA(lv_blank) = find( val = lv_name sub = ` ` ).
    IF lv_blank > 0.
      lv_name = lv_name(lv_blank).
    ENDIF.

    " '*_DPC' does not match 'ZCL_X_DPC_EXT', so the hand-written data provider
    " extension stays in review while the generated base class drops out.
    result = xsdbool( lv_name CP '*_MPC'
                   OR lv_name CP '*_MPC_EXT'
                   OR lv_name CP '*_DPC'
                   " The function group main program — SAP's own include list.
                   OR lv_name CP 'SAPL*' ).
  ENDMETHOD.


  METHOD is_deleted_object.
    " 'RPT' is the synthetic report row, not an object.
    CHECK is_part-type IS NOT INITIAL AND is_part-type <> 'RPT'.

    result = xsdbool( zcl_vx_vers_data=>check_part_exists(
                        i_type       = is_part-type
                        i_name       = is_part-object_name
                        i_class_name = CONV #( is_part-class ) ) = abap_false ).
  ENDMETHOD.


  METHOD diff_has_change_descr.
    DATA lv_opening_seen TYPE abap_bool.

    LOOP AT it_diff INTO DATA(ls_op).
      " Only what the NEW source holds: '=' and '+' tile it, a '-' line is gone
      " and cannot be the description of anything.
      CHECK ls_op-op = '=' OR ls_op-op = '+'.
      DATA(lv_trim) = condense( CONV string( ls_op-text ) ).
      CHECK lv_trim IS NOT INITIAL.

      IF is_full_line_comment( lv_trim ) = abap_true.
        IF ls_op-op = '+' AND line_names_request( ls_op-text ) = abap_true.
          result = abap_true.
          RETURN.
        ENDIF.
        CONTINUE.
      ENDIF.

      IF lv_opening_seen = abap_false AND is_opening_statement( lv_trim ) = abap_true.
        lv_opening_seen = abap_true.
        CONTINUE.
      ENDIF.

      " Code. Whatever comes after it is not the header of the object.
      RETURN.
    ENDLOOP.
  ENDMETHOD.


  METHOD is_full_line_comment.
    CHECK iv_line IS NOT INITIAL.
    IF iv_line(1) = '*' OR iv_line(1) = '"'.
      result = abap_true.
      RETURN.
    ENDIF.
    CHECK strlen( iv_line ) >= 2.
    result = xsdbool( iv_line(2) = '//' ).
  ENDMETHOD.


  METHOD is_opening_statement.
    DATA(lv_up) = to_upper( iv_line ).
    DATA(lv_word) = lv_up.
    DATA(lv_space) = find( val = lv_up sub = ` ` ).
    IF lv_space > 0.
      lv_word = lv_up(lv_space).
    ENDIF.
    REPLACE ALL OCCURRENCES OF `.` IN lv_word WITH ``.
    result = xsdbool( lv_word = 'REPORT'   OR lv_word = 'PROGRAM'
                   OR lv_word = 'FUNCTION' OR lv_word = 'FUNCTION-POOL'
                   OR lv_word = 'METHOD'   OR lv_word = 'FORM'
                   OR lv_word = 'MODULE'   OR lv_word = 'CLASS'
                   OR lv_word = 'INTERFACE' ).
  ENDMETHOD.


  METHOD set_review_scope.
    CLEAR gt_scope_korr.
    LOOP AT it_korrnums INTO DATA(ls_scope)
      WHERE sign = 'I' AND option = 'EQ' AND low IS NOT INITIAL.
      INSERT CONV trkorr( ls_scope-low ) INTO TABLE gt_scope_korr.
    ENDLOOP.
  ENDMETHOD.


  METHOD korr_in_scope.
    " No scope at all — a package or plain object review — so there is nothing
    " to be wrong against and every number is accepted.
    IF gt_scope_korr IS INITIAL.
      result = abap_true.
      RETURN.
    ENDIF.
    " Letter for letter against what was entered. Nothing is resolved on this
    " side: the point of the check is a number that reads right and is not.
    " KEEP (replaced): the found number used to be resolved to its parent K —
    "   DATA(lt_parents) = zcl_vx_request=>resolve_parent_k( iv_korr ).
    "   LOOP AT lt_parents ... IF line_exists( gt_scope_korr[ ... ] ).
    " with the note "a developer may write the number of a task or of a
    " transport of copies". True, and it made the check blind to the very thing
    " it exists for: a task of the reviewed request resolves INTO the request,
    " so ER6K9A1JDT passed a review of ER6K9A1JDL as long as it was one of its
    " tasks. The other direction is kept instead, where it is safe: a task
    " ENTERED on the selection screen brings its parent K into the scope
    " (MT_FILTER_PARENT_KORRNUMS), so a comment naming the K still passes.
    result = xsdbool( line_exists( gt_scope_korr[ table_line = iv_korr ] ) ).
  ENDMETHOD.


  METHOD block_request_verdict.
    DATA lt_refs TYPE ty_t_korr_found.
    LOOP AT it_lines INTO DATA(lv_line).
      line_request_refs(
        EXPORTING iv_line = lv_line
        CHANGING  ct_refs = lt_refs ).
    ENDLOOP.

    IF lt_refs IS INITIAL.
      result = '-'.
      RETURN.
    ENDIF.

    DATA lv_retrofit TYPE abap_bool.
    DATA lv_confirmed TYPE abap_bool.
    DATA lv_unknown  TYPE abap_bool.
    DATA lv_task     TYPE abap_bool.
    LOOP AT lt_refs INTO DATA(lv_ref).
      " Ours wins over everything else that may stand on the same lines.
      IF korr_in_scope( lv_ref ) = abap_true.
        result = 'X'.
        RETURN.
      ENDIF.
      IF is_other_system_korr( lv_ref ) = abap_true.
        lv_retrofit = abap_true.
        IF line_exists( it_obj_korrnums[ table_line = lv_ref ] ).
          lv_confirmed = abap_true.
        ENDIF.
      ELSE.
        korr_type(
          EXPORTING iv_korr    = lv_ref
          IMPORTING ev_exists  = DATA(lv_exists)
                    ev_is_task = DATA(lv_is_task) ).
        IF lv_exists = abap_false.
          lv_unknown = abap_true.
        ELSEIF lv_is_task = abap_true.
          lv_task = abap_true.
        ENDIF.
      ENDIF.
    ENDLOOP.
    " What can be proven about a number of ours outranks what can only be
    " observed about a number of another system.
    result = COND #( WHEN lv_unknown   = abap_true THEN 'N'
                     WHEN lv_task      = abap_true THEN 'T'
                     WHEN lv_confirmed = abap_true THEN 'V'
                     WHEN lv_retrofit  = abap_true THEN 'R'
                     ELSE                               'W' ).
  ENDMETHOD.


  METHOD is_other_system_korr.
    CHECK strlen( iv_korr ) >= 3.
    result = xsdbool( iv_korr(3) <> sy-sysid ).
  ENDMETHOD.


  METHOD korr_type.
    CLEAR: ev_exists, ev_is_task.

    READ TABLE gt_korr_exists INTO DATA(ls_known) WITH TABLE KEY korrnum = iv_korr.
    IF sy-subrc <> 0.
      SELECT SINGLE trfunction FROM e070
        WHERE trkorr = @iv_korr
        INTO @DATA(lv_trfunction).
      ls_known = VALUE #(
        korrnum = iv_korr
        exists  = xsdbool( sy-subrc = 0 )
        " S = development task, R = repair. Both are typed in by a developer and
        " released into the request; the request is what moves.
        is_task = xsdbool( sy-subrc = 0 AND ( lv_trfunction = 'S' OR lv_trfunction = 'R' ) ) ).
      INSERT ls_known INTO TABLE gt_korr_exists.
    ENDIF.

    ev_exists  = ls_known-exists.
    ev_is_task = ls_known-is_task.
  ENDMETHOD.


  METHOD line_request_refs.
    DATA(lv_cmt) = comment_of( iv_line ).
    CHECK strlen( lv_cmt ) >= 10.

    DATA lv_token TYPE string.
    DATA lv_pos   TYPE i.
    DATA(lv_len)  = strlen( lv_cmt ).
    " One character past the end, so the last token is examined like every other.
    WHILE lv_pos <= lv_len.
      DATA(lv_ch) = COND string( WHEN lv_pos < lv_len THEN lv_cmt+lv_pos(1) ELSE ` ` ).
      IF lv_ch CA c_alnum.
        lv_token = lv_token && lv_ch.
      ELSE.
        IF is_request_number( lv_token ) = abap_true.
          INSERT CONV trkorr( lv_token ) INTO TABLE ct_refs.
        ENDIF.
        CLEAR lv_token.
      ENDIF.
      lv_pos = lv_pos + 1.
    ENDWHILE.
  ENDMETHOD.


  METHOD update_stmt_open.
    DATA(lv_line) = CONV string( iv_line ).
    DATA(lv_trim) = condense( lv_line ).
    " Blank line — the statement around it is unaffected.
    CHECK lv_trim IS NOT INITIAL.
    " Full-line comment — likewise.
    IF lv_trim(1) = '*' OR lv_trim(1) = '"'.
      RETURN.
    ENDIF.

    " Only the code decides. A trailing comment may end in anything.
    DATA(lv_quote) = find( val = lv_line sub = `"` ).
    IF lv_quote >= 0.
      lv_line = substring( val = lv_line len = lv_quote ).
    ENDIF.
    lv_trim = condense( lv_line ).
    CHECK lv_trim IS NOT INITIAL.

    DATA(lv_last) = strlen( lv_trim ) - 1.
    cv_open = xsdbool( lv_trim+lv_last(1) <> '.' ).
  ENDMETHOD.


  METHOD comment_check_applies.
    result = xsdbool( iv_objtype <> 'CPUB'
                  AND iv_objtype <> 'CPRO'
                  AND iv_objtype <> 'CPRI'
                  AND iv_objtype <> 'CLSD'
                  AND NOT to_upper( iv_objname ) CP 'SAPL*' ).
  ENDMETHOD.


  METHOD line_names_request.
    DATA lt_refs TYPE ty_t_korr_found.
    line_request_refs(
      EXPORTING iv_line = iv_line
      CHANGING  ct_refs = lt_refs ).
    result = xsdbool( lt_refs IS NOT INITIAL ).
  ENDMETHOD.


  METHOD block_names_request.
    result = xsdbool( block_request_verdict( it_lines ) <> '-' ).
  ENDMETHOD.


  METHOD comment_of.
    DATA(lv_line) = to_upper( CONV string( iv_line ) ).
    DATA(lv_trim) = condense( lv_line ).
    CHECK lv_trim IS NOT INITIAL.

    " Comment line. CONDENSE first, like IS_COMMENTS_ONLY: a version source is
    " not guaranteed to have kept the '*' in column 1.
    IF lv_trim(1) = '*'.
      result = lv_trim.
      RETURN.
    ENDIF.

    " Trailing comment: ABAP opens one with '"', a CDS/DDL source with '//',
    " and on a line carrying both the first one wins. A '"' inside a string
    " literal — or the '//' of a URL — opens a comment that is none, and that
    " costs nothing here: what follows is searched for a request number, and a
    " literal carrying one names it just as well.
    DATA(lv_quote) = find( val = lv_line sub = `"` ).
    DATA(lv_slash) = find( val = lv_line sub = `//` ).
    DATA(lv_start) = COND i(
      WHEN lv_quote < 0                 THEN lv_slash
      WHEN lv_slash < 0                 THEN lv_quote
      WHEN lv_quote < lv_slash          THEN lv_quote
      ELSE                                   lv_slash ).
    CHECK lv_start >= 0.
    result = lv_line+lv_start.
  ENDMETHOD.


  METHOD is_request_number.
    CHECK strlen( iv_token ) = 10.
    " The system id starts with a letter; a token opening with a digit is a date
    " or an amount, not a request.
    CHECK iv_token(1) CA c_letters.
    CHECK iv_token+3(1) CA `KT`.
    " At least one digit behind the category letter: 'ABCDEFGHIJ' is not a
    " request number, 'ER6K9A1JDL' is.
    CHECK iv_token+4(6) CA c_digits.
    result = abap_true.
  ENDMETHOD.


  METHOD strip_generated_ts_diff.
    DATA lt_del TYPE zif_vx_vers_types=>ty_t_diff.
    DATA lt_ins TYPE zif_vx_vers_types=>ty_t_diff.

    LOOP AT it_diff INTO DATA(ls_op).
      CASE ls_op-op.
        WHEN '-'. APPEND ls_op TO lt_del.
        WHEN '+'. APPEND ls_op TO lt_ins.
        WHEN OTHERS.
          " '=' boundary: flush the accumulated change run, then keep the eq line
          flush_ts_run( CHANGING ct_del = lt_del
                                 ct_ins = lt_ins
                                 ct_out = result ).
          APPEND ls_op TO result.
      ENDCASE.
    ENDLOOP.
    " flush a trailing change run (diff not ending on an '=' line)
    flush_ts_run( CHANGING ct_del = lt_del
                           ct_ins = lt_ins
                           ct_out = result ).
  ENDMETHOD.


  METHOD flush_ts_run.
    DATA lt_eq TYPE zif_vx_vers_types=>ty_t_diff.

    " Pair each generated-timestamp deletion with a generated-timestamp
    " insertion in the same run and collapse the pair to an unchanged line
    " (keeping the new text). Unmatched generated lines stay as real changes.
    LOOP AT ct_del ASSIGNING FIELD-SYMBOL(<del>) WHERE op = '-'.
      IF is_generated_ts_line( <del>-text ) = abap_false.
        CONTINUE.
      ENDIF.
      LOOP AT ct_ins ASSIGNING FIELD-SYMBOL(<ins>) WHERE op = '+'.
        IF is_generated_ts_line( <ins>-text ) = abap_true.
          APPEND VALUE #( op = '=' text = <ins>-text ) TO lt_eq.
          <ins>-op = 'X'.   " mark as consumed
          <del>-op = 'X'.
          EXIT.
        ENDIF.
      ENDLOOP.
    ENDLOOP.

    LOOP AT ct_del INTO DATA(ls_d) WHERE op = '-'. APPEND ls_d TO ct_out. ENDLOOP.
    LOOP AT ct_ins INTO DATA(ls_i) WHERE op = '+'. APPEND ls_i TO ct_out. ENDLOOP.
    APPEND LINES OF lt_eq TO ct_out.

    CLEAR ct_del.
    CLEAR ct_ins.
  ENDMETHOD.

ENDCLASS.
